# Generated by Django 5.2.16 on 2026-09-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_contactlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, upload_to="profile/"),
        ),
    ]
