# Generated by Django 5.2.16 on 2026-09-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image_alt_text",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
