# Generated by Django 5.2.16 on 2026-09-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_profile_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(blank=True, default="", upload_to="documents/"),
        ),
    ]
